name: dddd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0  
  table_calendar: ^3.0.0
  persistent_bottom_nav_bar: ^5.0.2
  intl: ^0.17.0
  firebase_core:
  firebase_auth:
  google_sign_in:
  http:

flutter_localizations:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  
flutter:
  uses-material-design: true
  assets:
    - images/photo_1.png
    - images/photo_2.png
    - images/ppf3-300x225.png
    - images/Questionnaire-300x222.png
    - images/EMPERCE_THE_UNIQUNESS.png
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
